-- MOVETI real social interactions
create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists post_likes_post_id_idx
  on public.post_likes(post_id);

create index if not exists post_comments_post_id_created_at_idx
  on public.post_comments(post_id, created_at);

alter table public.post_likes enable row level security;
alter table public.post_comments enable row level security;

drop policy if exists "post likes readable" on public.post_likes;
create policy "post likes readable"
on public.post_likes for select
to authenticated
using (true);

drop policy if exists "users can create own likes" on public.post_likes;
create policy "users can create own likes"
on public.post_likes for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can delete own likes" on public.post_likes;
create policy "users can delete own likes"
on public.post_likes for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "comments readable" on public.post_comments;
create policy "comments readable"
on public.post_comments for select
to authenticated
using (true);

drop policy if exists "users can create own comments" on public.post_comments;
create policy "users can create own comments"
on public.post_comments for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can delete own comments" on public.post_comments;
create policy "users can delete own comments"
on public.post_comments for delete
to authenticated
using (auth.uid() = user_id);
